### PR TITLE
correcting some function names

### PR DESCRIPTION
**Pull request by abdulhannanali**
At first I wasn't able to find the function for the changes I updated. I tried a few similar values and found out the correct ones

### CODE REVIEW

**Comment by abdulhannanali** [comment]
I wasn't able to find function for **miscAddMovieRating** also can you please tell me how can I console.log the names of all the functions in node. So I can find the ones I want to use directly. It displays this when I console.log my mdb object
```
MovieDB { api_key:  'my api key' }
```

**Comment by impronunciable** [comment]
Hi. You just need to modify this place https://github.com/impronunciable/moviedb/blob/master/lib/endpoints.json

**Comment by abdulhannanali** [comment]
@impronunciable oh okay thanks! That's pretty cool! You are using JSON. Thanks for the response but you may still merge the branch if you want since I've corrected two of 'em to default ones :smile:

**Comment by abdulhannanali** [comment]
Since there's already a pull request correcting the same thing. I am closing this PR. Thanks @impronunciable very appreciated.

**Pull request closed without merging**
