### PR TITLE
Updating superagent and using new syntax

### PR DESCRIPTION
**Pull request by angelxmoreno**

### CODE REVIEW

**Comment by angelxmoreno** [comment]
takes care of #33 which will allow us to us cache as mentioned in #32 
Please review before merging.

**Comment by impronunciable** [comment]
Thanks!

I just merged another pr so it says this is in conflict. I'll gladly merge this if you can merge your branch with current master

**Comment by angelxmoreno** [comment]
fixining it soon

**Comment by impronunciable** [comment]
Thank you :)

**Comment by angelxmoreno** [comment]
new PR merged into this one. Tests pass.

**Comment by impronunciable** [comment]
Thanks

**Pull request merged**
