### PR TITLE
Add etag and if-modified-since support.

### PR DESCRIPTION
**Pull request by oeuillot**
Add etag and if-modified-since support.  (for http request)
The execMethod() returns a third parameter which is the http response object.
(In order to get the date and the etag header values)

Etag is not supported by the platform (but an issue is still opened)

### CODE REVIEW

**Comment by oeuillot** [comment]
Thanks :-)

**Comment by impronunciable** [comment]
Thank you!

**Comment by oeuillot** [comment]
Can you make a new version and publish the npm ?

Regards,

2016-03-14 18:00 GMT+01:00 Dan Zajdband <notifications@github.com>:

**Comment by impronunciable** [comment]
Yes, give me a few hours :)

**Comment by oeuillot** [comment]
Ok take your time ...

2016-03-15 12:04 GMT+01:00 Dan Zajdband <notifications@github.com>:

**Comment by impronunciable** [comment]
@oeuillot Version 0.2.3 let me know if there's something missing

thanks for the help

**Pull request merged**
