### PR TITLE
Added endpoints for Recommended and Similar TV shows

### PR DESCRIPTION
**Pull request by sharepointalex**
Added endpoints for recommendations and similar

### CODE REVIEW

**Comment by impronunciable** [comment]
@sharepointalex thanks for the pr. Similar is already in place https://github.com/impronunciable/moviedb/blob/master/lib/endpoints.json#L55

can you just leave `recommendations` so I can merge and bump the version?

Thank you!

**Comment by sharepointalex** [comment]
@impronunciable ah I must've missed that similar was there already.

I will remove it and leave recommendations.

Cheers

**Comment by impronunciable** [comment]
Thanks!

**Comment by sharepointalex** [comment]
Nice one - might be a dumb question but when installing from npm will this update be in there?

**Pull request merged**
